apiVersion: batch/v1
kind: Job
metadata:
  generateName: benchmark-
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: perftest
          image: harbor-tkg.vmware.env.com/library/perf-test:2.11.0
          args:
            - "--uri"
            - "amqp://V53PNSgePVMvYG1ncAn2i9Q9XL1DOtHY:4unalqm_MOKW1aXavhSpQafba9iurYEl@red.rabbitmq-red.svc:5672/%2f"
            - "--producers"
            - "1"
            - "--consumers"
            - "2"
            - "--flag"
            - "persistent"
            - "--auto-delete"
            - "false"
            - "--size"
            - "100"
            - "--qos"
            - "10"
            - "--multi-ack-every"
            - "5"
            - "--confirm"
            - "100"
            - "--confirm-timeout"
            - "1"
            - "--queue"
            - "benchmark"
            - "--routing-key"
            - "benchmark"
            - "--time"
            - "60"
