apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    replicas: 3
    resources: 
      requests:
        memory: 32Gi
        cpu: "16"
      limits:
        memory: 32Gi
        cpu: "16"
    readinessProbe: 
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    image: quay.io/strimzi/kafka:0.31.0-kafka-3.2.1
    listeners:
      - name: plain
        port: 9092 
        type: internal 
        tls: false 
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      num.network.threads: 8
      num.io.threads: 16
      background.threads: 16
      socket.send.buffer.bytes: 1048576
      socket.receive.buffer.bytes: 1048576
      socket.request.max.bytes: 104857600
    storage: 
      type: persistent-claim
      class: default
      size: 6Ti
    metricsConfig: 
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef: 
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper: 
    replicas: 3 
    resources:
      requests:
        memory: 8Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "2"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 500Gi
      class: default
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
