apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: rec
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
  redisOnFlashSpec:
    enabled: true
    flashStorageEngine: rocksdb
    storageClassName: default
    flashDiskSize: 100G
 
